language: java

sudo: true

jdk: oraclejdk8

before_script:
  - psql -c 'CREATE DATABASE fullstop;' -U postgres
#  - psql -c "ALTER USER postgres WITH PASSWORD 'postgres';" -U postgres

script:
    - mvn clean install -Pfullstop-startup,pg-travis --batch-mode
