language: java

sudo: true

jdk: oraclejdk8

services:
    - postgresql

#before_script:
#  - psql -c 'CREATE DATABASE fullstop;' -U postgres
#  - psql -c "ALTER USER postgres WITH PASSWORD 'postgres';" -U postgres

script:
    - psql -c 'CREATE DATABASE fullstop;' -U postgres
    - mvn clean verify -Pintegration-test,pg-travis --batch-mode

box:
    type: jfy
