language: java

sudo: true

jdk: oraclejdk8

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'CREATE DATABASE fullstop;' -U postgres
#  - psql -c "ALTER USER postgres WITH PASSWORD 'postgres';" -U postgres

script:
    - mvn clean verify -Pintegration-test,pg-travis -U

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
      on_failure: change
