language: java
jdk:
  - oraclejdk8

script: mvn clean install

after_success:
  - mvn coveralls:report -Ptravis

notifications:
    email:
      on_failure: change
    webhooks:
        urls:
          - https://webhooks.gitter.im/e/c3da3727316a21be0f19
        on_success: change
        on_failure: always
        on_start: false

