language: java

jdk: oraclejdk8

script:
    - mvn clean verify -Pintegration-test -U

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
      on_failure: change
