language: java
jdk:
  - oraclejdk8

services:
    - postgresql

before_script:
  - psql -c 'create database fullstop;' -U postgres

script: mvn clean install

after_success:
  - mvn coveralls:report -Ptravis

notifications:
    email:
      on_failure: change
    webhooks:
        urls:
          - https://webhooks.gitter.im/e/5a095b6bac7576bf3e78
        on_success: always
        on_failure: always
        on_start: false

