swagger: "2.0"

info:
  version: "0.0.1-alpha"
  title: Fullstop API
  description: Audit reporting

schemes:
  - https

basePath: /api/

consumes:
  - application/json
produces:
  - application/json

definitions:
  Violation:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 1
      version:
        type: integer
        format: int64
        example: 3
      eventId:
        type: string
        example: cd768599e1bb41c38279c26254feff5cf57bf967
      account_id:
        type: string
        example: 123456789
      region:
        type: string
        example: "eu-west-1"
      meta_info:
        type: object
        example: ""
      # add also plugin name
      # and violation type obj
      comment:
        type: string
        example: "Was a patch on Friday and I was alone in the office"
      created:
        type: string
        format: date-time
        example: 2015-05-21T10:24:47.788-02:00
      created_by:
        type: string
        example: "John Die"
      last_modified:
        type: string
        format: date-time
        example: 2015-05-21T10:24:47.788-02:00
      last_modified_by:
        type: string
        example: "John Dae"


  LogObj:
    type: object
    properties:
      log_type:
        type: string
        enum:
          - AUDIT_LOG
          - USER_DATA
      instance_id:
        type: string
        example: "i-123kd"
      account_id:
        type: string
        example: "1233456568"
      region:
        type: string
        example: "eu-west-1"
      instance_boot_time:
        type: string
        format: date-time
        example: 2015-05-21T10:24:47.788-02:00
      log_data:
        type: string
        example: ""

paths:

  ## Fullstop API v1

  /api/violations/{id}:
    get:
      summary: violation
      description: Get one violation
      tags:
        - Fullstop API
      operationId: getViolation
      security:
        - oauth2: [uid]
      parameters:
        - name: id
          in: path
          type: integer
          format: int64
          required: true
      responses:
        "200":
          description: Violation
          schema:
            $ref: "#/definitions/Violation"

  /api/violations:
    get:
      summary: violations
      description: Get all violations
      tags:
        - Fullstop API
      operationId: violations
      security:
        - oauth2: [uid]
      parameters:
        - name: accounts
          in: query
          description: Include only violations in these accounts
          required: false
          type: array
          items:
            type: string
        - name: since
          in: query
          required: false
          type: string
          format: date-time
          description: Include only violations that happened after this point in time
        - name: last-violation
          in: query
          required: false
          type: integer
          format: int64
          description: Include only violations after the one with this id
        - name: checked
          in: query
          required: false
          type: boolean
          description: Include only violations where checked field equals this value
      responses:
        "200":
          description: List of all violations
          schema:
            type: array
            items:
              $ref: "#/definitions/Violation"

  /api/violations/{id}/resolution:
    post:
      summary: Resolve and explain this violation
      description: Resolve and explain violation
      tags:
        - Fullstop API
      operationId: resolveViolations
      security:
        - oauth2: [uid]
      responses:
        "200":
          description: Violation resolved successfully
      parameters:
        - name: id
          in: path
          type: integer
          required: true
        - name: comment
          in: body
          required: true
          schema:
            type: string

  /api/instance-logs:
    post:
      summary: Put instance log in S3
      description: Add log for instance in S3
      tags:
        - Fullstop API
      operationId: instanceLogs
      security:
        - oauth2: [uid]
      responses:
        "201":
          description: Logs saved successfully
      parameters:
        - name: log
          in: body
          required: true
          schema:
            $ref: "#/definitions/LogObj"
            description: log metadata and object

securityDefinitions:
  oauth2:
    type: oauth2
    flow: password
    tokenUrl: https://example.com/oauth2/tokenUrl
    scopes:
      uid: Unique identifier of the user accessing the service.
